//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace utro
{
    using System;
    using System.Collections.Generic;
    
    public partial class fabricStorage
    {
        public int id { get; set; }
        public string article { get; set; }
        public int width { get; set; }
        public int length { get; set; }
    
        public virtual fabric fabric { get; set; }
    }
}
